server:
  address: 0.0.0.0
activemq:
  brokerUrl: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
  concurrency: ${ACTIVEMQ_CONCURRENCY:1}
queue:
  name: ${QUEUE_NAME:mainQueue}
worker:
  name: ${HOSTNAME:worker1}
  enabled: ${WORKER_ENABLED:true}
store:
  enabled: ${STORE_ENABLED:true}
