apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  namespace: horizontal-pod-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: web
          image: fogsyio/activemq:arm64v8-5.15.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 61616
          resources:
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: queue
  namespace: horizontal-pod-autoscaler
spec:
  ports:
    - port: 61616
      targetPort: 61616
  selector:
    app: queue