apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: horizontal-pod-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: backend
          image: siralexander/horizontal-pod-autoscalar-arm64:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ACTIVEMQ_BROKER_URL
              value: "tcp://queue:61616"
            - name: ACTIVEMQ_CONCURRENCY
              value: "1"
            - name: STORE_ENABLED
              value: "false"
            - name: WORKER_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: horizontal-pod-autoscaler
spec:
  ports:
    - name: backend-web
      port: 8071
      targetPort: 8080
  selector:
    app: backend
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: horizontal-pod-autoscaler
#  annotations:
#    key: string
#  labels:
#    key: string
spec: #.spec
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: backend-web