apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: horizontal-pod-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: siralexander/horizontal-pod-autoscalar-arm64:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ACTIVEMQ_BROKER_URL
              value: "tcp://queue:61616"
            - name: ACTIVEMQ_CONCURRENCY
              value: "1"
            - name: STORE_ENABLED
              value: "true"
            - name: WORKER_ENABLED
              value: "false"
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: horizontal-pod-autoscaler
spec:
  ports:
    - name: frontend-web
      port: 8070
      targetPort: 8080
  selector:
    app: frontend
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: horizontal-pod-autoscaler
#  annotations:
#    key: string
#  labels:
#    key: string
spec: #.spec
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: frontend-web